### ISSUE TITLE
Mk4 page - section heading cut off at certain screen sizes

### ISSUE THREAD

**Issue by siim-m** [sunday-afternoon-design/coldcard#4]
This seems to be related to the width/height combination, not just width itself:

<img width="2493" alt="image" src="https://github.com/user-attachments/assets/0c98a319-24ad-4ede-b4a3-7ccd04dd7001">

**Comment by SimonFrr** [comment]
quick fix for this: https://github.com/sunday-afternoon-design/coldcard/commit/cab14bc1d049cacd82d8de417b0fab212d513ff5

**Comment by SimonFrr** [comment]
note that the padding on top of that section is big for some screen sizes, it can be fixed under individual breakpoints in the `.main-sec-5.main-mk4-sec-5` selector—I'm just wondering if these paddings were designed to compensate the way the horizontal scroll section functions, and since my fix modifies that a little bit I'm wondering about unintended consequences

**Comment by siim-m** [comment]
I think that's good enough, at least I didn't notice any side effects for now. Will implement and let you know if anything pops up.
